In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/Users/estyle-150/github/my_signage/data/processed/processed20240826.csv')
df.columns

Index(['datetime', 'y', 'client', 'close', 'price_am', 'price_pm', 'is_train',
       'price', 'year', 'month', 'weekday', 'y_lag_365', 'price_am_lag_1',
       'price_am_lag_7', 'price_am_lag_365', 'price_pm_lag_1',
       'price_pm_lag_7', 'price_pm_lag_365', 'price_am_moving_avg_7',
       'price_am_moving_avg_30', 'price_pm_moving_avg_7',
       'price_pm_moving_avg_30', 'day'],
      dtype='object')

In [3]:
train_df = df[df['is_train']==1]
test_df = df[df['is_train']==0]
test_df

,datetime,y,client,close,price_am,price_pm,is_train,price,year,month,...,price_am_lag_7,price_am_lag_365,price_pm_lag_1,price_pm_lag_7,price_pm_lag_365,price_am_moving_avg_7,price_am_moving_avg_30,price_pm_moving_avg_7,price_pm_moving_avg_30,day
2101,2016-04-01,0,1,0,3.0,2.0,0,2.5,2016,4,...,4.0,2.0,4.0,5.0,2.0,4.428571,2.400000,3.857143,2.266667,1
2102,2016-04-02,0,0,0,5.0,5.0,0,5.0,2016,4,...,5.0,2.0,2.0,5.0,1.0,4.428571,2.566667,3.857143,2.433333,2
2103,2016-04-03,0,1,0,2.0,2.0,0,2.0,2016,4,...,5.0,4.0,5.0,4.0,3.0,4.000000,2.600000,3.571429,2.500000,3
2104,2016-04-04,0,1,0,1.0,1.0,0,1.0,2016,4,...,4.0,2.0,2.0,4.0,2.0,3.571429,2.566667,3.142857,2.500000,4
2105,2016-04-05,0,0,0,1.0,1.0,0,1.0,2016,4,...,4.0,1.0,1.0,4.0,1.0,3.142857,2.566667,2.714286,2.500000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2461,2017-03-27,0,0,0,5.0,4.0,0,4.5,2017,3,...,3.0,5.0,4.0,4.0,4.0,3.857143,2.166667,4.000000,2.166667,27
2462,2017-03-28,0,0,0,4.0,4.0,0,4.0,2017,3,...,4.0,4.0,4.0,4.0,4.0,3.857143,2.233333,4.000000,2.233333,28
2463,2017-03-29,0,0,0,3.0,3.0,0,3.0,2017,3,...,2.0,4.0,4.0,4.0,4.0,4.000000,2.266667,3.857143,2.266667,29
2464,2017-03-30,0,0,0,4.0,3.0,0,3.5,2017,3,...,3.0,5.0,3.0,2.0,4.0,4.142857,2.333333,4.000000,2.300000,30
2465,2017-03-31,0,1,0,5.0,4.0,0,4.5,2017,3,...,4.0,5.0,3.0,5.0,4.0,4.285714,2.433333,3.857143,2.400000,31

In [4]:
# 学習データ
train = train_df.iloc[:-365]
y_train = train['y']              #目的変数y
x_train = train.drop('y', axis=1) #説明変数X

# テストデータ
test = train_df.iloc[-365:]  #テストデータ
y_test = test['y']              #目的変数y
X_test = test.drop('y', axis=1) #説明変数X

In [5]:
import optuna
import xgboost as xgb
from sklearn import model_selection
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.inspection import PartialDependenceDisplay
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'optuna'

In [12]:
regressor = xgb.XGBRegressor()
regressor.fit(x_train.values, y_train.values)

NameError: name 'xgb' is not defined

In [6]:
conda install optuna

Channels:
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - optuna

Current channels:

  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



Note: you may need to restart the kernel to use updated packages.